### PR TITLE
Replace sucker with suck

### PR DESCRIPTION
**Pull request by Extarys**
https://github.com/sqids/sqids-javascript/issues/21#issuecomment-1892340031

When generating the wordlist, would it be ok to also add the variants S -> 5. `a55hole`, `5ucker` ?

### CODE REVIEW

**Comment by 4kimov** [comment]
Hi @Extarys, thank you for the PR. A few adjustments are needed:

1. All new changes go to the `next` branch, not `main`: https://github.com/sqids/sqids-blocklist?tab=readme-ov-file#adding-or-adjusting-data
2. You just need to change one word in `data/en.json` and then run `cargo run` so that it automatically generates the proper output (no need to mess with number variations, that will be done automatically)

**Comment by Extarys** [comment]
> You just need to change one word in data/en.json and then run cargo run so that it automatically generates the proper output (no need to mess with number variations, that will be done automatically)

Ahhh RIP, that is what I thought initially :facepalm: thanks and sorry!

**Comment by Extarys** [comment]
@4kimov Sorry I forgot to ask about the substitution.

Should I include `S` -> `5` ?  5UCK, 5LUT, A55HOLE ?

**Comment by 4kimov** [comment]
@Extarys No, you should avoid manually including substitutions/leetspeak (the code will do that part). Basically you just need to remove the "er" from that line.

**Comment by Extarys** [comment]
@4kimov I know that :smile: 
I meant here: https://github.com/sqids/sqids-blocklist/blob/5dcc156d210c2c050655ac0a76d8e163fdfac0cb/src/utils.rs#L60

Or do you prefer to stick with those original substitution like the README says?

**Comment by 4kimov** [comment]
@Extarys Ah sorry, I misunderstood. No, these replacements have been adjusted by testing what visually makes sense. They will be reviewed for the next major version, but for now we're just interested in collecting a proper blocklist for as many languages as we can.

**Pull request closed without merging**
