### PR TITLE
fix german blocklist

### PR DESCRIPTION
**Pull request by mgred**
replace non offensive word _deich_. This seems to be a wrong translation from _dyke_ which means _levee_. It can also mean _lesbe_, that describes a female homosexual person.

### CODE REVIEW

**Comment by mgred** [comment]
I ran `cargo run` and included the output in the PR, that seems to be wrong isn't it?

**Comment by 4kimov** [comment]
Thank you @mgred, much appreciated. No, the changed files look correct. Is there something that you see should be adjusted before I merge?

**Comment by mgred** [comment]
@4kimov I'm concerned, because the pull request adding the [indonesian blocklist](https://github.com/sqids/sqids-blocklist/pull/4/files) did not include the generated output files and the combined `blocklist.json`. These outputs are included in this PR. I think we have to generate the outputs including the indonesian files first before we can merge this.

**Comment by mgred** [comment]
I created a [PR](https://github.com/sqids/sqids-blocklist/pull/6) that adds `output/id.json` and updates `output/blocklist.json` with the indonesian wordlist.

**Comment by 4kimov** [comment]
Ah, I see! Thank you for elaborating.

No, the programmatically generated output doesn't matter yet in the `next` branch, because at this point the most important (and hardest) thing is to gather appropriate lists. The output will be generated / cleaned up either way sooner or later.

Good eye tho 👍

**Pull request merged**
